/* ═══════════════════════════════════════════
   data.js  —  All province & territory data
═══════════════════════════════════════════ */

const ALL_REGIONS = [
  {
    emoji:'🏙️', he:'אונטריו', en:'Ontario', abbr:'ON',
    capital_he:'אוטווה', capital_en:'Ottawa',
    capital_lat:45.4215, capital_lng:-75.6972,
    largest_he:'טורונטו', largest_en:'Toronto',
    region_he:'מרכז קנדה', region_en:'Central Canada',
    flower_he:'פרח הטריליום הלבן', flower_en:'White Trillium',
    pop:14900000, pop_he:'14.9 מיליון', area_km2:1076395,
    fun_he:'אונטריו היא הפרובינציה עם הכי הרבה תושבים! בטורונטו גרים אנשים מיותר מ-200 מדינות.',
    fun_en:'Ontario is the most populated province! Toronto has people from over 200 countries.',
    flag_url:'https://upload.wikimedia.org/wikipedia/commons/8/88/Flag_of_Ontario.svg',
    color:'#2a7ab8', territory:false, lat:51.25, lng:-85.32
  },
  {
    emoji:'⚜️', he:'קוויבק', en:'Québec', abbr:'QC',
    capital_he:'קוויבק סיטי', capital_en:'Quebec City',
    capital_lat:46.8139, capital_lng:-71.2082,
    largest_he:'מונטריאול', largest_en:'Montreal',
    region_he:'מרכז קנדה', region_en:'Central Canada',
    flower_he:'סיגלית כחולה', flower_en:'Blue Flag Iris',
    pop:8700000, pop_he:'8.7 מיליון', area_km2:1542056,
    fun_he:'קוויבק היא הפרובינציה הגדולה ביותר בשטח! קנדה מייצרת 70% מסירופ האדר בעולם — רובו מקוויבק.',
    fun_en:"Quebec is the largest province by area! Canada produces 70% of the world's maple syrup — mostly from Quebec.",
    flag_url:'https://upload.wikimedia.org/wikipedia/commons/5/5f/Flag_of_Quebec.svg',
    color:'#236b43', territory:false, lat:53.0, lng:-71.0
  },
  {
    emoji:'🏔️', he:'בריטיש קולומביה', en:'British Columbia', abbr:'BC',
    capital_he:'ויקטוריה', capital_en:'Victoria',
    capital_lat:48.4284, capital_lng:-123.3656,
    largest_he:'ונקובר', largest_en:'Vancouver',
    region_he:'מערב קנדה', region_en:'Western Canada',
    flower_he:'מגנוליה', flower_en:'Pacific Dogwood',
    pop:5400000, pop_he:'5.4 מיליון', area_km2:944735,
    fun_he:'בבריטיש קולומביה יש הרים מושלגים וחופים יפים! הדוב הלבן "דוב הרוח" חי רק שם.',
    fun_en:'BC has snowy mountains AND beautiful beaches! The rare white "Spirit Bear" lives only here.',
    flag_url:'https://upload.wikimedia.org/wikipedia/commons/b/b8/Flag_of_British_Columbia.svg',
    color:'#6b3fa0', territory:false, lat:53.73, lng:-127.65
  },
  {
    emoji:'🌾', he:'אלברטה', en:'Alberta', abbr:'AB',
    capital_he:'אדמונטון', capital_en:'Edmonton',
    capital_lat:53.5461, capital_lng:-113.4938,
    largest_he:'קלגרי', largest_en:'Calgary',
    region_he:'פריריות', region_en:'The Prairies',
    flower_he:'ורד הפרא', flower_en:'Wild Rose',
    pop:4800000, pop_he:'4.8 מיליון', area_km2:661848,
    fun_he:'בפארק הלאומי בנף יש אגמים טורקיז מדהימים. אלברטה — הפרובינציה היחידה בלי מיסים מחוזיים!',
    fun_en:'Banff National Park has stunning turquoise lakes. Alberta is the only province with no provincial sales tax!',
    flag_url:'https://upload.wikimedia.org/wikipedia/commons/f/f5/Flag_of_Alberta.svg',
    color:'#c8741a', territory:false, lat:53.93, lng:-116.58
  },
  {
    emoji:'🌊', he:'נובה סקוטיה', en:'Nova Scotia', abbr:'NS',
    capital_he:'האליפקס', capital_en:'Halifax',
    capital_lat:44.6488, capital_lng:-63.5752,
    largest_he:'האליפקס', largest_en:'Halifax',
    region_he:'מחוזות המפרץ', region_en:'Maritime Provinces',
    flower_he:'פרח המייפלאואר', flower_en:'Mayflower',
    pop:1020000, pop_he:'1.0 מיליון', area_km2:55284,
    fun_he:'נובה סקוטיה = "סקוטלנד החדשה". הגאות הגבוהה בעולם — עד 16 מטר פעמיים ביום!',
    fun_en:"Nova Scotia = \"New Scotland\". World's highest tides — up to 16 meters (52 ft) twice a day!",
    flag_url:'https://upload.wikimedia.org/wikipedia/commons/c/c0/Flag_of_Nova_Scotia.svg',
    color:'#2a7ab8', territory:false, lat:45.0, lng:-63.0
  },
  {
    emoji:'🌿', he:'מניטובה', en:'Manitoba', abbr:'MB',
    capital_he:'ויניפג', capital_en:'Winnipeg',
    capital_lat:49.8951, capital_lng:-97.1384,
    largest_he:'ויניפג', largest_en:'Winnipeg',
    region_he:'פריריות', region_en:'The Prairies',
    flower_he:'פרח הכרוקוס הפרוח', flower_en:'Prairie Crocus',
    pop:1400000, pop_he:'1.4 מיליון', area_km2:647797,
    fun_he:"מניטובה — בירת הדובים הקוטביים! בעיר צ'רצ'יל ניתן לראות דובים קוטביים בנובמבר.",
    fun_en:'Manitoba is the Polar Bear Capital! In Churchill you can watch polar bears waiting for Hudson Bay to freeze.',
    flag_url:'https://upload.wikimedia.org/wikipedia/commons/a/a7/Flag_of_the_Province_of_Manitoba.svg',
    color:'#236b43', territory:false, lat:56.42, lng:-98.74
  },
  {
    emoji:'🌾', he:"ססקצ'ואן", en:'Saskatchewan', abbr:'SK',
    capital_he:"רג'ינה", capital_en:'Regina',
    capital_lat:50.4452, capital_lng:-104.6189,
    largest_he:'ססקטון', largest_en:'Saskatoon',
    region_he:'פריריות', region_en:'The Prairies',
    flower_he:'שושן הפרריות האדום', flower_en:'Western Red Lily',
    pop:1200000, pop_he:'1.2 מיליון', area_km2:651036,
    fun_he:"ססקצ'ואן — הפרובינציה הכי שטוחה! ניתן לראות אופק על מרחק של יותר מ-100 ק\"מ.",
    fun_en:'Saskatchewan is the flattest province! You can see the horizon over 100km away.',
    flag_url:'https://upload.wikimedia.org/wikipedia/commons/b/bb/Flag_of_Saskatchewan.svg',
    color:'#c8741a', territory:false, lat:55.0, lng:-106.0
  },
  {
    emoji:'🦞', he:'ניו בראנסוויק', en:'New Brunswick', abbr:'NB',
    capital_he:'פרדריקטון', capital_en:'Fredericton',
    capital_lat:45.9636, capital_lng:-66.6431,
    largest_he:'מונקטון', largest_en:'Moncton',
    region_he:'מחוזות המפרץ', region_en:'Maritime Provinces',
    flower_he:'סיגלית', flower_en:'Purple Violet',
    pop:830000, pop_he:'830 אלף', area_km2:72908,
    fun_he:'ניו בראנסוויק — הפרובינציה הדו-לשונית הרשמית היחידה! אנגלית + צרפתית.',
    fun_en:"New Brunswick is Canada's only officially bilingual province! English + French.",
    flag_url:'https://upload.wikimedia.org/wikipedia/commons/f/fb/Flag_of_New_Brunswick.svg',
    color:'#c41e3a', territory:false, lat:46.57, lng:-66.46
  },
  {
    emoji:'🦅', he:'פרינס אדוורד איילנד', en:'Prince Edward Island', abbr:'PEI',
    capital_he:'שרלוטאון', capital_en:'Charlottetown',
    capital_lat:46.2382, capital_lng:-63.1311,
    largest_he:'שרלוטאון', largest_en:'Charlottetown',
    region_he:'מחוזות המפרץ', region_en:'Maritime Provinces',
    flower_he:'נעל הגברת (סחלב)', flower_en:"Lady's Slipper",
    pop:180000, pop_he:'180 אלף', area_km2:5660,
    fun_he:"PEI — הפרובינציה הקטנה ביותר! מפורסמת כמקום הולדתה של 'אן מהבית הירוק'.",
    fun_en:"PEI is the smallest province! Famous as the birthplace of 'Anne of Green Gables'.",
    flag_url:'https://upload.wikimedia.org/wikipedia/commons/d/d7/Flag_of_Prince_Edward_Island.svg',
    color:'#c8741a', territory:false, lat:46.51, lng:-63.42
  },
  {
    emoji:'🐟', he:'ניופאונדלנד ולברדור', en:'Newfoundland & Labrador', abbr:'NL',
    capital_he:"סנט ג'ונס", capital_en:"St. John's",
    capital_lat:47.5605, capital_lng:-52.7126,
    largest_he:"סנט ג'ונס", largest_en:"St. John's",
    region_he:'קנדה האטלנטית', region_en:'Atlantic Canada',
    flower_he:'צמח המלכודת', flower_en:'Pitcher Plant',
    pop:540000, pop_he:'540 אלף', area_km2:405212,
    fun_he:"ניופאונדלנד — הפרובינציה הכי מזרחית! ויקינגים הגיעו אליה 500 שנה לפני קולומבוס.",
    fun_en:'Newfoundland is the most eastern province! Vikings arrived 500 years before Columbus.',
    flag_url:'https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Newfoundland_and_Labrador.svg',
    color:'#2a7ab8', territory:false, lat:53.14, lng:-57.66
  },
  {
    emoji:'❄️', he:'יוקון', en:'Yukon', abbr:'YT',
    capital_he:'וייטהורס', capital_en:'Whitehorse',
    capital_lat:60.7212, capital_lng:-135.0568,
    largest_he:'וייטהורס', largest_en:'Whitehorse',
    region_he:'צפון מערב', region_en:'Northwestern Canada',
    flower_he:'פרח האש', flower_en:'Fireweed',
    pop:43000, pop_he:'43 אלף', area_km2:482443,
    fun_he:'ביוקון ניתן לראות את זוהר הצפון! בקיץ השמש כמעט ולא שוקעת.',
    fun_en:'In Yukon you can see the Northern Lights! In summer the sun barely sets.',
    flag_url:'https://upload.wikimedia.org/wikipedia/commons/6/69/Flag_of_Yukon.svg',
    color:'#6b3fa0', territory:true, lat:64.0, lng:-135.0
  },
  {
    emoji:'🐻‍❄️', he:'טריטוריות הצפון-מערב', en:'Northwest Territories', abbr:'NT',
    capital_he:'ילוונייף', capital_en:'Yellowknife',
    capital_lat:62.4540, capital_lng:-114.3718,
    largest_he:'ילוונייף', largest_en:'Yellowknife',
    region_he:'הצפון הגדול', region_en:'The Far North',
    flower_he:'פרח הסלע הצפוני', flower_en:'Mountain Avens',
    pop:45000, pop_he:'45 אלף', area_km2:1346106,
    fun_he:'ממלכת היהלומים של קנדה! בחורף הטמפרטורה יורדת עד מינוס 50 מעלות!',
    fun_en:'Diamond capital of Canada! In winter temperatures drop to -50°C (-58°F)!',
    flag_url:'https://upload.wikimedia.org/wikipedia/commons/c/c1/Flag_of_the_Northwest_Territories.svg',
    color:'#2a7ab8', territory:true, lat:64.83, lng:-124.85
  },
  {
    emoji:'🌨️', he:'נונאווט', en:'Nunavut', abbr:'NU',
    capital_he:'איקאלוויט', capital_en:'Iqaluit',
    capital_lat:63.7467, capital_lng:-68.5170,
    largest_he:'איקאלוויט', largest_en:'Iqaluit',
    region_he:'הארקטיק', region_en:'The Arctic',
    flower_he:'פרג ארקטי', flower_en:'Purple Saxifrage',
    pop:40000, pop_he:'40 אלף', area_km2:2093190,
    fun_he:"נונאווט נוסד ב-1999 — הטריטוריה הצעירה! 85% אינואיטים. 'נונאווט' = 'האדמה שלנו'.",
    fun_en:"Nunavut was created in 1999 — the newest! 85% Inuit. 'Nunavut' means 'Our Land'.",
    flag_url:'https://upload.wikimedia.org/wikipedia/commons/9/90/Flag_of_Nunavut.svg',
    color:'#236b43', territory:true, lat:70.30, lng:-83.11
  }
];

const PROVINCES   = ALL_REGIONS.filter(r => !r.territory);
const TERRITORIES = ALL_REGIONS.filter(r =>  r.territory);
const MAX_POP     = Math.max(...ALL_REGIONS.map(r => r.pop));
const MAX_AREA    = Math.max(...ALL_REGIONS.map(r => r.area_km2));

// ── Quiz questions ────────────────────────────
const QUIZ_Q = [
  {he:'מהי הבירה של קנדה?', en:'What is the capital of Canada?',
   opts_he:['טורונטו','אוטווה','ונקובר','מונטריאול'], opts_en:['Toronto','Ottawa','Vancouver','Montreal'],
   c:1, exp_he:'אוטווה היא בירת קנדה, נמצאת במחוז אונטריו.', exp_en:"Ottawa is Canada's capital, in Ontario."},
  {he:'איזו פרובינציה היא הגדולה ביותר בשטח?', en:'Largest province by area?',
   opts_he:['אונטריו','בריטיש קולומביה','קוויבק','נונאווט'], opts_en:['Ontario','BC','Quebec','Nunavut'],
   c:2, exp_he:'קוויבק היא הפרובינציה הגדולה ביותר.', exp_en:'Quebec is the largest province.'},
  {he:'מהי העיר הגדולה ביותר בקנדה?', en:"Canada's largest city?",
   opts_he:['מונטריאול','ונקובר','קלגרי','טורונטו'], opts_en:['Montreal','Vancouver','Calgary','Toronto'],
   c:3, exp_he:'טורונטו היא העיר הגדולה ביותר.', exp_en:"Toronto is Canada's largest city."},
  {he:'כמה פרובינציות יש בקנדה?', en:'How many provinces?',
   opts_he:['7','8','10','12'], opts_en:['7','8','10','12'],
   c:2, exp_he:'בקנדה יש 10 פרובינציות ו-3 טריטוריות.', exp_en:'Canada has 10 provinces and 3 territories.'},
  {he:'מהי הפרובינציה המייצרת הכי הרבה סירופ אדר?', en:'Most maple syrup?',
   opts_he:['אונטריו','מניטובה','קוויבק','נובה סקוטיה'], opts_en:['Ontario','Manitoba','Quebec','Nova Scotia'],
   c:2, exp_he:'קוויבק מייצרת כ-70% מסירופ האדר בעולם!', exp_en:"Quebec produces 70% of the world's maple syrup!"},
  {he:'איפה יש את הגאות הגבוהה ביותר בעולם?', en:"World's highest tides?",
   opts_he:['BC','ניו בראנסוויק','נובה סקוטיה','ניופאונדלנד'], opts_en:['BC','New Brunswick','Nova Scotia','Newfoundland'],
   c:2, exp_he:'מפרץ פאנדי בנובה סקוטיה — עד 16 מטר!', exp_en:'Bay of Fundy, Nova Scotia — up to 16 meters!'},
  {he:'מהי הטריטוריה הצעירה ביותר?', en:"Canada's newest territory?",
   opts_he:['יוקון','נונאווט','טריטוריות הצפון-מערב','אלברטה'], opts_en:['Yukon','Nunavut','NWT','Alberta'],
   c:1, exp_he:'נונאווט נוסד ב-1999.', exp_en:'Nunavut was created in 1999.'},
  {he:'מהי הפרובינציה הקטנה ביותר?', en:'Smallest province?',
   opts_he:['נובה סקוטיה','ניו בראנסוויק','PEI','ניופאונדלנד'], opts_en:['Nova Scotia','New Brunswick','PEI','Newfoundland'],
   c:2, exp_he:'פרינס אדוורד איילנד (PEI) היא הקטנה.', exp_en:'Prince Edward Island (PEI) is the smallest.'},
  {he:'איזו פרובינציה ידועה בדובים הקוטביים?', en:'Polar bear province?',
   opts_he:['יוקון','מניטובה','נונאווט',"ססקצ'ואן"], opts_en:['Yukon','Manitoba','Nunavut','Saskatchewan'],
   c:1, exp_he:"מניטובה (צ'רצ'יל) — בירת הדובים הקוטביים!", exp_en:'Manitoba (Churchill) — Polar Bear Capital!'},
  {he:'מהי הבירה של בריטיש קולומביה?', en:"BC's capital?",
   opts_he:['ונקובר','ויקטוריה','קלוונה',"פרינס ג'ורג'"], opts_en:['Vancouver','Victoria','Kelowna','Prince George'],
   c:1, exp_he:'ויקטוריה — לא ונקובר!', exp_en:'Victoria — not Vancouver!'},
  {he:"מה פירוש 'נונאווט'?", en:"What does 'Nunavut' mean?",
   opts_he:['האדמה שלנו','הצפון הגדול','ארץ הקרח','הגבול הצפוני'], opts_en:['Our Land','The Great North','Land of Ice','Northern Border'],
   c:0, exp_he:"'נונאווט' = 'האדמה שלנו' באינוקטיטוט.", exp_en:"'Nunavut' means 'Our Land' in Inuktitut."},
  {he:'מהי הפרובינציה הדו-לשונית הרשמית?', en:'Only bilingual province?',
   opts_he:['קוויבק','מניטובה','ניו בראנסוויק','אונטריו'], opts_en:['Quebec','Manitoba','New Brunswick','Ontario'],
   c:2, exp_he:'ניו בראנסוויק — אנגלית + צרפתית רשמית.', exp_en:'New Brunswick — English + French officially.'},
  {he:'מהי הפרובינציה עם הכי הרבה תושבים?', en:'Most populated province?',
   opts_he:['קוויבק','בריטיש קולומביה','אלברטה','אונטריו'], opts_en:['Quebec','BC','Alberta','Ontario'],
   c:3, exp_he:'אונטריו — כ-14.9 מיליון תושבים!', exp_en:'Ontario — about 14.9 million people!'},
  {he:'מהי בירת אלברטה?', en:"Alberta's capital?",
   opts_he:['קלגרי','אדמונטון',"לת'בריג'",'רד דיר'], opts_en:['Calgary','Edmonton','Lethbridge','Red Deer'],
   c:1, exp_he:'אדמונטון היא הבירה — לא קלגרי!', exp_en:'Edmonton is the capital — not Calgary!'},
];

// ── Timeline events ───────────────────────────
const TIMELINE = [
  {year:1867, he:'הקמת קנדה — 4 מחוזות מקוריים', en:'Canada founded — 4 original provinces',
   regions:['אונטריו','קוויבק','נובה סקוטיה','ניו בראנסוויק'],
   desc_he:'חוק צפון אמריקה הבריטית איחד 4 קולוניות לכדי מדינה אחת ביום 1 יולי.',
   desc_en:'The British North America Act united 4 colonies on July 1st.',
   color:'#c41e3a', type:'found'},
  {year:1870, he:'השטחים הצפון-מערביים נוצרים', en:'Northwest Territories established',
   regions:['טריטוריות הצפון-מערב'],
   desc_he:"קנדה רכשה את שטחי חברת Hudson's Bay (Rupert's Land) ויצרה את השטחים הצפון-מערביים — שטח עצום שממנו יצאו מאוחר יותר יוקון, אלברטה, ססקצ'ואן ונונאווט.",
   desc_en:"Canada bought Rupert's Land from the Hudson's Bay Company and created the Northwest Territories — a vast region that later gave birth to Yukon, Alberta, Saskatchewan, and Nunavut.",
   color:'#2a7ab8', type:'terr'},
  {year:1870, he:'מניטובה', en:'Manitoba',
   regions:['מניטובה'],
   desc_he:'לאחר מרידת המטיס של לואי ריאל ב-1869, מניטובה הצטרפה כמחוז קטן מאוד — כינויה היה "מחוז בול הדואר".',
   desc_en:'After Louis Riel\'s Red River Resistance, Manitoba joined as a small "postage stamp" province.',
   color:'#236b43', type:'prov'},
  {year:1871, he:'בריטיש קולומביה', en:'British Columbia',
   regions:['בריטיש קולומביה'],
   desc_he:'הצטרפה בתנאי שתיבנה מסילת רכבת חוצת-קנדה תוך 10 שנים.',
   desc_en:'Joined on condition Canada build a transcontinental railway within 10 years.',
   color:'#6b3fa0', type:'prov'},
  {year:1873, he:'פרינס אדוורד איילנד', en:'Prince Edward Island',
   regions:['פרינס אדוורד איילנד'],
   desc_he:'הצטרפה אחרי שקנדה הבטיחה לממן טלגרף ושירות מעבורת לאי.',
   desc_en:'Joined after Canada promised to fund a telegraph and ferry service to the island.',
   color:'#c8741a', type:'prov'},
  {year:1898, he:'טריטוריות יוקון', en:'Yukon Territory',
   regions:['יוקון'],
   desc_he:'נוסדה בעקבות בהלת הזהב קלונדייק שמשכה 100,000 מחפשי זהב.',
   desc_en:'Created during the Klondike Gold Rush that drew 100,000 prospectors.',
   color:'#6b3fa0', type:'terr'},
  {year:1905, he:"אלברטה וססקצ'ואן", en:'Alberta & Saskatchewan',
   regions:['אלברטה',"ססקצ'ואן"],
   desc_he:'שתי פרובינציות חדשות נוצרו מהשטחים הצפון-מערביים בגלל גל הגירה גדול.',
   desc_en:'Two new provinces carved from the NWT due to a massive wave of prairie settlement.',
   color:'#c8741a', type:'prov'},
  {year:1949, he:'ניופאונדלנד', en:'Newfoundland',
   regions:['ניופאונדלנד ולברדור'],
   desc_he:'ההצבעה עברה ברוב של 52.3% בלבד — הצטרפות הכי מאוחרת לקנדה.',
   desc_en:'The vote passed by just 52.3% — the last province to join Canada.',
   color:'#2a7ab8', type:'prov'},
  {year:1999, he:'נונאווט', en:'Nunavut',
   regions:['נונאווט'],
   desc_he:'הטריטוריה הצעירה ביותר — נוצרה כשטח עצמאי לאינואיטים. לאחר הפרדתה, גבולות הצפון-מערב הצטמצמו לצורתם הנוכחית.',
   desc_en:'The newest territory — created as a self-governing homeland for the Inuit. After its separation, the NWT shrank to its current boundaries.',
   color:'#236b43', type:'terr'},
  {year:1999, he:'טריטוריות הצפון-מערב — גבולות נוכחיים', en:'Northwest Territories — current boundaries',
   regions:['טריטוריות הצפון-מערב'],
   desc_he:'לאחר שנונאווט הופרדה ב-1999, טריטוריות הצפון-מערב קיבלו את הגבולות שלהן כיום. הטריטוריה עדיין גדולה פי 3 מצרפת!',
   desc_en:'After Nunavut split off in 1999, the NWT settled into its current shape — still three times the size of France!',
   color:'#2a7ab8', type:'terr'},
];
